#!/bin/sh

set -e

WEBTHINGS_HOME=$(realpath "$(dirname $(realpath $0))/..")

NODE=$(which node)

DEST_SERVICE_FILE=/etc/systemd/system/webthings-home.service
sudo test -f "{DEST_SERVICE_FILE}" && sudo rm "${DEST_SERVICE_FILE}"
cat "${WEBTHINGS_HOME}/scripts/webthings-home.service" | sed s\\node\\"${NODE}"\\ | sudo tee "${DEST_SERVICE_FILE}" > /dev/null
